### ISSUE TITLE
The unknown folder request for training and testing

### ISSUE THREAD

**Issue by thptai** [Cuixxx/ProFD#2]
Hello, thanks for your contribution.

I have tried to run the code, and the inference and testing require the below folders from the Market-1501 dataset.

`bounding_box_test_resize
bounding_box_train_resize
query_resize`

It would be a big help if you could provide instructions on achieving those folders.

**Comment by Cuixxx** [comment]
Thanks for your kind words! These folders are generated with [resize.py]( https://github.com/Cuixxx/ProFD/blob/master/resize.py) in our project. If you have any other problems, feel free to contact me! :)
